CREATE TABLE COUNTRY_MASTER (
  COUNTRY_ID NUMBER(10), 
  COUNTRY_CODE VARCHAR2(20),
  COUNTRY_NAME VARCHAR2(20),
  PRIMARY KEY (COUNTRY_ID)
 );
 
 
CREATE TABLE STATE_MASTER (
  STATE_ID NUMBER(10), 
  COUNTRY_ID NUMBER(10), 
  STATE_NAME VARCHAR2(20), 
  PRIMARY KEY (STATE_ID)
);
 
CREATE TABLE CITY_MASTER (
  CITY_ID NUMBER(10), 
  STATE_ID NUMBER(10),
  CITY_NAME VARCHAR2(20),
  PRIMARY KEY (CITY_ID)
);
  